<?php

namespace AppBundle\Entity;

/**
 * MovieRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOrdered($maxResults = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('m')
          ->from('AppBundle:Movie', 'm')
          ->orderBy('m.name', 'ASC');

        if ($maxResults) {
            $qb->setMaxResults($maxResults);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
