<?php

namespace AppBundle\Entity;

/**
 * ProjectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectionRepository extends \Doctrine\ORM\EntityRepository
{
}
