<?php

$movies = array(
    array('name' => 'The Shawshank Redemption','year' => 1994,'genre' => 'Horror','length' => 142),
    array('name' => 'Forrest Gump','year' => 1994,'genre' => 'Comedy','length' => 106),
    array('name' => 'The Green Mile','year' => 1999,'genre' => 'Crime','length' => 82),
    array('name' => 'One Flew Over the Cuckoo\'s Nest','year' => 1975,'genre' => 'Thriller','length' => 104),
    array('name' => 'Schindler\'s List','year' => 1993,'genre' => 'Drama','length' => 155),
    array('name' => 'Seven','year' => 1995,'genre' => 'History','length' => 244),
    array('name' => 'The Godfather','year' => 1972,'genre' => 'Film-Noir','length' => 286),
    array('name' => 'Intouchables','year' => 2011,'genre' => 'Family','length' => 265),
    array('name' => '12 Angry Men','year' => 1957,'genre' => 'Animation','length' => 197),
    array('name' => 'The Godfather: Part II','year' => 1974,'genre' => 'Romance','length' => 274),
    array('name' => 'Pelíšky','year' => 1999,'genre' => 'Horror','length' => 259),
    array('name' => 'Once Upon a Time in the West','year' => 1968,'genre' => 'Comedy','length' => 253),
    array('name' => 'Pulp Fiction','year' => 1994,'genre' => 'Crime','length' => 186),
    array('name' => 'Terminator 2: Judgment Day','year' => 1991,'genre' => 'Thriller','length' => 225),
    array('name' => 'The Silence of the Lambs','year' => 1991,'genre' => 'Drama','length' => 135),
    array('name' => 'The Lord of the Rings: The Fellowship of the Ring','year' => 2001,'genre' => 'History','length' => 160),
    array('name' => 'The Dark Knight','year' => 2008,'genre' => 'Film-Noir','length' => 131),
    array('name' => 'The Good, the Bad and the Ugly','year' => 1966,'genre' => 'Family','length' => 142),
    array('name' => 'The Matrix','year' => 1999,'genre' => 'Animation','length' => 182),
    array('name' => 'Rain Man','year' => 1988,'genre' => 'Romance','length' => 183),
    array('name' => 'Raiders of the Lost Ark','year' => 1981,'genre' => 'Horror','length' => 239),
    array('name' => 'The Magnificent Seven','year' => 1960,'genre' => 'Comedy','length' => 281),
    array('name' => 'Earth','year' => 2007,'genre' => 'Crime','length' => 192),
    array('name' => 'The Sting','year' => 1973,'genre' => 'Thriller','length' => 107),
    array('name' => 'Aliens','year' => 1986,'genre' => 'Drama','length' => 140),
    array('name' => 'Alien','year' => 1979,'genre' => 'History','length' => 256),
    array('name' => 'Higher Principle','year' => 1960,'genre' => 'Film-Noir','length' => 93),
    array('name' => 'Indiana Jones and the Last Crusade','year' => 1989,'genre' => 'Family','length' => 237),
    array('name' => 'Die Hard','year' => 1988,'genre' => 'Animation','length' => 283),
    array('name' => 'Leon','year' => 1994,'genre' => 'Romance','length' => 151),
    array('name' => 'Butch Cassidy and the Sundance Kid','year' => 1969,'genre' => 'Horror','length' => 260),
    array('name' => 'L. A. Confidential','year' => 1997,'genre' => 'Comedy','length' => 206),
    array('name' => 'Cesta do hlubin študákovy duše','year' => 1939,'genre' => 'Crime','length' => 252),
    array('name' => 'City of God','year' => 2002,'genre' => 'Thriller','length' => 106),
    array('name' => 'Amadeus','year' => 1984,'genre' => 'Drama','length' => 160),
    array('name' => 'Star Wars: Episode V - The Empire Strikes Back','year' => 1980,'genre' => 'History','length' => 272),
    array('name' => 'Obecná škola','year' => 1991,'genre' => 'Film-Noir','length' => 146),
    array('name' => 'Spalovač mrtvol','year' => 1968,'genre' => 'Family','length' => 163),
    array('name' => '„Marečku, podejte mi pero!“','year' => 1976,'genre' => 'Animation','length' => 211),
    array('name' => 'S čerty nejsou žerty','year' => 1984,'genre' => 'Romance','length' => 94),
    array('name' => 'Saving Private Ryan','year' => 1998,'genre' => 'Horror','length' => 136),
    array('name' => 'A Beautiful Mind','year' => 2001,'genre' => 'Comedy','length' => 280),
    array('name' => 'Dances with Wolves','year' => 1990,'genre' => 'Crime','length' => 148),
    array('name' => 'Inception','year' => 2010,'genre' => 'Thriller','length' => 134),
    array('name' => 'Casino','year' => 1995,'genre' => 'Drama','length' => 158),
    array('name' => ' Back to the Future','year' => 1985,'genre' => 'History','length' => 104),
    array('name' => 'The Shining','year' => 1980,'genre' => 'Film-Noir','length' => 164),
    array('name' => 'Heat','year' => 1995,'genre' => 'Family','length' => 110),
    array('name' => 'Vesničko má středisková','year' => 1985,'genre' => 'Animation','length' => 158),
    array('name' => 'The Pianist','year' => 2002,'genre' => 'Romance','length' => 190),
    array('name' => 'American History X','year' => 1998,'genre' => 'Horror','length' => 194),
    array('name' => 'Life Is Beautiful','year' => 1997,'genre' => 'Comedy','length' => 98),
    array('name' => 'The Usual Suspects','year' => 1995,'genre' => 'Crime','length' => 191),
    array('name' => 'Gladiator','year' => 2000,'genre' => 'Thriller','length' => 259),
    array('name' => 'Fight Club','year' => 1999,'genre' => 'Drama','length' => 186),
    array('name' => 'The Sixth Sense','year' => 1999,'genre' => 'History','length' => 283),
    array('name' => 'Star Wars: Episode IV - A New Hope','year' => 1977,'genre' => 'Film-Noir','length' => 217),
    array('name' => 'Platoon','year' => 1986,'genre' => 'Family','length' => 105),
    array('name' => 'Once Upon a Time in America','year' => 1984,'genre' => 'Animation','length' => 285),
    array('name' => 'The Lord of the Rings: The Two Towers','year' => 2002,'genre' => 'Romance','length' => 239),
    array('name' => 'Million Dollar Baby','year' => 2004,'genre' => 'Horror','length' => 98),
    array('name' => 'Lethal Weapon','year' => 1987,'genre' => 'Comedy','length' => 272),
    array('name' => 'Senna','year' => 2010,'genre' => 'Crime','length' => 138),
    array('name' => 'Psycho','year' => 1960,'genre' => 'Thriller','length' => 281),
    array('name' => 'Roman Holiday','year' => 1953,'genre' => 'Drama','length' => 196),
    array('name' => 'Papillon','year' => 1973,'genre' => 'History','length' => 265),
    array('name' => 'Braveheart','year' => 1995,'genre' => 'Film-Noir','length' => 203),
    array('name' => 'The Prestige','year' => 2006,'genre' => 'Family','length' => 195),
    array('name' => 'Some Like It Hot','year' => 1959,'genre' => 'Animation','length' => 140),
    array('name' => 'The Twelve Tasks of Asterix','year' => 1976,'genre' => 'Romance','length' => 219),
    array('name' => 'U pokladny stál...','year' => 1943,'genre' => 'Horror','length' => 81),
    array('name' => 'Warrior','year' => 2011,'genre' => 'Comedy','length' => 257),
    array('name' => 'Good Will Hunting','year' => 1997,'genre' => 'Crime','length' => 193),
    array('name' => 'Requiem for a Dream','year' => 2000,'genre' => 'Thriller','length' => 141),
    array('name' => 'Witches\' Hammer','year' => 1969,'genre' => 'Drama','length' => 149),
    array('name' => 'Django Unchained','year' => 2012,'genre' => 'History','length' => 172),
    array('name' => 'The Bourne Ultimatum','year' => 2007,'genre' => 'Film-Noir','length' => 290),
    array('name' => 'Goodfellas','year' => 1990,'genre' => 'Family','length' => 174),
    array('name' => 'Shutter Island','year' => 2010,'genre' => 'Animation','length' => 189),
    array('name' => 'Snatch.','year' => 2000,'genre' => 'Romance','length' => 274),
    array('name' => 'Cool Hand Luke','year' => 1967,'genre' => 'Horror','length' => 124),
    array('name' => 'American Beauty','year' => 1999,'genre' => 'Comedy','length' => 175),
    array('name' => 'Na samotě u lesa','year' => 1976,'genre' => 'Crime','length' => 198),
    array('name' => 'Star Wars: Episode III - Revenge of the Sith','year' => 2005,'genre' => 'Thriller','length' => 257),
    array('name' => 'Cesta do pravěku','year' => 1955,'genre' => 'Drama','length' => 211),
    array('name' => 'Trainspotting','year' => 1996,'genre' => 'History','length' => 164),
    array('name' => 'Star Wars: Episode VI - Return of the Jedi','year' => 1983,'genre' => 'Film-Noir','length' => 213),
    array('name' => 'Seven Samurai','year' => 1954,'genre' => 'Family','length' => 295),
    array('name' => 'The Last Boy Scout','year' => 1991,'genre' => 'Animation','length' => 172),
    array('name' => 'The Hunt','year' => 2012,'genre' => 'Romance','length' => 249),
    array('name' => 'Awakenings','year' => 1990,'genre' => 'Horror','length' => 165),
    array('name' => 'The Bear','year' => 1988,'genre' => 'Comedy','length' => 256),
    array('name' => 'The Butterfly Effect','year' => 2004,'genre' => 'Crime','length' => 261),
    array('name' => 'American Gangster','year' => 2007,'genre' => 'Thriller','length' => 105),
    array('name' => 'Jára Cimrman ležící, spící','year' => 1983,'genre' => 'Drama','length' => 182),
    array('name' => 'Lock, Stock and Two Smoking Barrels','year' => 1998,'genre' => 'History','length' => 81),
    array('name' => 'Shrek','year' => 2001,'genre' => 'Film-Noir','length' => 127),
);
